### ISSUE TITLE
Duplicate AMQ operator

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#108]
Is there a way to reduce the footprint of Kafka by consolidating two AMQ operators into one? BAS and IoT require Kafkfa. The AMQ and BAS both deploy AMQ operators separately into multiple projects, which seems redundant.

**Comment by durera** [comment]
The operators themselves only carry a minor footprint.  It's the clusters that are the main footprint really, and I don't think we would recommend sharing a Kafka cluster between MAS and BAS.

MAS can support the AMQ Streams operator being deployed with cluster scope rather than namespace scope if the user prefers, however every other application in the cluster would also need to support this, if BAS can be used with a cluster scoped AMQ streams operator we could make this change, but I don't know whether that's possible or not.  We will try to find out.

**Comment by durera** [comment]
Closing issue based on above answer
