### ISSUE TITLE
Deploying MAS Manage on AWS Self manage openshift cluster facing issue with insufficient ephemeral storage available on worker nodes

### ISSUE THREAD

**Issue by ekambaraml** [ibm-mas/ansible-devops#1202]
we are facing an issue with Manage Build with error "Insufficient ephemeral storage"

even though the node has 300GB

![image](https://github.com/ibm-mas/ansible-devops/assets/26153008/a028345a-2187-4426-9db0-76ecdbad3944)

**Comment by ekambaraml** [comment]
Client used this tech note to temporarily fix the issue https://www.ibm.com/support/pages/build-process-fails-error-%E2%80%9Cinsufficient-ephemeral-storage%E2%80%9D-when-deploying-manage-maximo-application-suite

they are looking for the root cause and permanent fix.

**Comment by andrercm** [comment]
By default Manage operator does required ephemeral storage from cluster's node to unpack Manage build in order to install it in the cluster. That's something handled exclusively by Manage operator, unfortunately this is something not handled and there's no action by the provisioning automation. 
Here's the link to open a support case with MAS or Manage application in case you need further clarification: https://www.ibm.com/mysupport/s/?language=en_US
