### ISSUE TITLE
Adding options to selectively mirror operators in mirror_ocp role.

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#1282]
Adding option to selectively mirror operators in `mirror_ocp` role can help reducing mirror file size.
For example, we don't need `NVIDIA GPU Operator` for Manage only MAS instance.

Also, adding `LVM Storage Operator` would be nice for single node configuration.

**Comment by durera** [comment]
Although I like the idea of it being configurable, I don't think we are likely to ever support this, we are already stepping beyond what we originally wanted to own by providing a pre-defined definition of a MAS subset of the Red Hat operator catalogs.  For cases where a customer wants to further customize I think that's going to lie within their own processes & procedures for managing their cluster; we want to keep `mirror_ocp` and `mirror-redhat-images` relatively straight forward as it's more a bonus than a core part of what we're wanting to focus on (which is MAS).  It exists because many customers have struggled with the base tooling provided by Red Hat, but to be able to maintain it we need to keep it relatively simple with minimal variations.

We can certainly look at adding the LVM Storage Operator to the set though.
