### ISSUE TITLE
[Ansible] - Allow to provide ansible variables via inventory instead of environment variable

### ISSUE THREAD

**Issue by Delgon** [ibm-mas/ansible-devops#1489]
### Feature and motivation

Currently, playbooks and some ansible roles load their variables from environment variables (eg: mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') | default('9.0.x', true) }}")

To follow ansible best practices and also allow to use playbooks & roles from a classic ansible method via inventories. It would be necessary to unlock the loading of these variables so that we can provide them via inventory OR environment variable.

### Usage example

https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#inventory-basics-formats-hosts-and-groups

**Comment by whitfiea** [comment]
@Delgon This should be already possible as the majority of the default role vars can be overridden by an inventory or play vars, see https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence for variable precedence.

The example you gave of `mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') | default('9.0.x', true) }}")` is from a play var and so would be higher than a inventory var. In this case you would be best to create your own playbooks that either use inventory files or your own var files, and these would override any role defaults. For example the role default for mas_catalog_source is here https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_install/defaults/main.yml#L4 but if you have a play var or inventory var of `mas_catalog_source: blah` then this would be used instead.

You might want to also look at the just released execution environment as detailed here image https://ibm-mas.github.io/ansible-devops/execution-environment/ as this also doesn't use environment variables.

**Comment by durera** [comment]
As @whitfiea states, the majority of parameters throughout the collection allow the use of inventories, as the env vars are looked up in the role defaults, which are the lowest priority precedence-wise.

There are a few cases where env vars are looked up outside of the defaults, but those are not intentional and are treated as bugs.  e.g. there's one I opened a looooooong time ago here for this in regards to some Maximo Manage variables that are handled the wrong way and prevent the use of normal expected Ansible usage patterns:  
- https://github.com/ibm-mas/ansible-devops/issues/519

**Comment by durera** [comment]
Thanks, I'll track this under the existing #519 going forward.
