### ISSUE TITLE
Support auto-install of the oc & ibmcloud clients

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#2]
To simplify usage, we should auto-download the `oc` and `ibmcloud` tools (in any roles that require them) to simplity the user experience.  The download/extract commands for these can be found in the docker image, however we must make sure that we handle different platforms gracefully .. either limit the auto-download support to specific platforms (and document as such) or make it work universally ... I'm mostly thinking about the usual "Mac problem" here :) 

Alternatively can we actually remove the use of `ibmcloud` and `oc` entirely and just call their APIs/use their ansible modules, that would simplify things even more.

**Comment by robbinmav** [comment]
I support the idea of downloading the oc client.
The oc client is going to be an important tool for administrators who want to automate tasks.

It is important to make sure that administrators can easily download files to the client PC e.g. via cp or rsync.
The must gather tools look for rsync which isn't installed on windows by default.

In that case it would be useful to have the option of automatically downloading and configuring cygwin.
However it would be worth considering how to make rsync available as well.

Setting up cygwin to include rsync isn't obvious because rsync isn't listed as one of the available packages... in the default installation screens.

**Comment by durera** [comment]
This is pretty much redundant now we are using the CLI image, so closing this issue
