### ISSUE TITLE
ManageWorkspace activation failed

### ISSUE THREAD

**Issue by jiangmonge** [ibm-mas/ansible-devops#482]
I have an OCP cluster on-prem. Manage application deployed successful however activating in workspace failed.  maxinst pod will never get created even after hours. 

When I checked the status of CRD "ManageWorkspace" instance conditions,  it shows failure Child does not exist.  What child is missing? How can I get the ManageWorkspace instance created successfully.

**Comment by johnnykp** [comment]
What's your MAS_APP_CHANNEL parameter? I tried few days ago with 8.4 and it was not working, tried to change to 8.3.x and could complete the installation

**Comment by durera** [comment]
This is more a problem with the product than the Ansible collection based on the discussion above.  If there are issues with the Manage application please contact support, this repository is for issues with the Ansible collection that drives the install, rather than problems using what has been installed.
