### ISSUE TITLE
In airgap installation, TektonAddons still to pull yaml from raw.githubusercontent.com

### ISSUE THREAD

**Issue by liupinyi** [ibm-mas/ansible-devops#495]
TA
[addon](https://console-openshift-console.apps.cpd.ibm.com/k8s/cluster/operator.tekton.dev~v1alpha1~TektonAddon/addon)
Get "https://raw.githubusercontent.com/tektoncd/catalog/master/task/jib-maven/0.4/jib-maven.yaml": dial tcp: lookup raw.githubusercontent.com on 172.30.0.10:53: server misbehaving

![image](https://user-images.githubusercontent.com/21214618/198188864-418b4767-71eb-47fc-94b6-0e76f4d9b660.png)

**Comment by hughjfchen** [comment]
Did you solve this? we all know this url can not be accessed within China.

**Comment by durera** [comment]
Does this cause a failure while running the pipeline, or is it just a case of an annoying error message polluting the system that would like to remove?  We haven't noticed this in other disconnected environments, so I'm wondering whether it caused any fatal errors for you?

**Comment by hughjfchen** [comment]
It would definitely cause a failure if it needs to access this address during running for us because this address has been blocked in China.发自我的手机-------- 原始邮件 --------发件人： David Parker ***@***.***>日期： 2022年11月15日周二 22:40收件人： ibm-mas/ansible-devops ***@***.***>抄送： Hugh JF Chen ***@***.***>, Comment ***@***.***>主    题： Re: [ibm-mas/ansible-devops] In airgap installation, TektonAddons still to pull yaml from raw.githubusercontent.com (Issue #495)
Does this cause a failure while running the pipeline, or is it just a case of an annoying error message polluting the system that would like to remove?  We haven't noticed this in other disconnected environments, so I'm wondering whether it caused any fatal errors for you?

**Comment by hughjfchen** [comment]
@durera I haven't tested it yet(I'm still struggling transferring the over 80G airgap registry tarball to customer) but if the 
pipeline needs to access the above address during installation it would definitely cause a failure for customers in China 
because the above address has been blocked in China. I guess the manifests needed to download during installation 
could be put to `github release` page and then could be downloaded by customers located any countries.

**Comment by durera** [comment]
The MAS install pipeline doesn't access that .. I'm not sure what that is doing tbh, but it's not something we are using/taking advantage of, so it shouldn't impact the MAS install.

**Comment by hughjfchen** [comment]
Great to hear that. I'll keep an eye on this during the installation and see what will happen.

**Comment by liupinyi** [comment]
thank you. It occurred in an Airgap installation.

**Comment by hughjfchen** [comment]
So, it will cause the airgap installation fail? If so, how did you solve it?

**Comment by durera** [comment]
We've done multiple installs in airgap environments now and not seen this in any, so closing the issue here.  If still seeing problems with this then should probably raise a support ticket so that the team can get debug information from the cluster as I don't think it's normal to see this.
