### ISSUE TITLE
ocp release and operator mirror only support direct mode

### ISSUE THREAD

**Issue by hughjfchen** [ibm-mas/ansible-devops#514]
From the source code, currently the OCP release and operator mirror can only support `direct` mirror and 
totally ignore `MIRROR_MODE` environment variable. Should add `MIRROR_MODE` support or document 
this clearly.

**Comment by durera** [comment]
Updates here to address this for the OCP release catalog.

OCP operator catalog mirroring is currently broken ... I have raised a support ticket with Red Hat which has resulted in this JIRA ticket: https://issues.redhat.com/browse/OCPBUGS-3801

Once this is resolved by Red Hat we will look at restoring catalog image mirroring to the Ansible collection (and ensuring it supports direct, to-filesystem, and from-filesystem modes), until then it's disabled entirely.

**Comment by witekwww** [comment]
@durera i have not tested these changes, but looking at the yaml (ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/redhat-catalogs.yml.j2) i'm pretty sure that this will not work - sorry
oc mirror produces flawed yamls for CatalogSource. Some operators depend on the names of those CatalogSources and if You compare them from connected installation to what oc mirror produces You will spot differences in names , eg.: certified-operator-index instead of certified-operators.
I was struggling with that some time ago just to find that changing the name fixed the problem.
