### ISSUE TITLE
Create a role to extract the Manage maxinst/updatedb/tdtoolkit logs from the maxinst pod

### ISSUE THREAD

**Issue by jcrg99** [ibm-mas/ansible-devops#674]
I am not sure if there is any role that does that, but would be great to have a role to extract the logs from the maxinst pod (install/updatedb/tdtoolkit logs) and save somewhere, in a bucket for example, or even local folder. These logs might not persist when maxinst is restarted and then the logs are lost for good. 

This is the location of the logs inside the maxinst pod: /opt/IBM/SMP/maximo/tools/maximo/log

**Comment by andrercm** [comment]
We do have a role that stores the logging from server bundles into COS buckets, but I don't think it does store the logs for maxinst pod... Also this seems like something that Manage operator should deal with, might not be something that the automation would do on behalf of it? I'm saying that because the existing automation just configures ManageWorkspace CR to have `s3logging` properties defined and pointing to a COS instance: 

Here are more details about it:
https://github.com/ibm-mas/ansible-devops/tree/master/ibm/mas_devops/roles/suite_manage_logging_config
