### ISSUE TITLE
MAS installation with cli/ansible-devops tool can't set the upgrade method of Manage to 'Manual'

### ISSUE THREAD

**Issue by ysuzuki01** [ibm-mas/ansible-devops#679]
When installing MAS + Manage using cli/ansible-devops tools, even if we want to configure the upgrade method of Manage with "Manual", cli/ansible-devops tools will always be composed of "Channel Subscription". 
This setting cannot be changed later.

For settings that cannot be changed after Manage is deployed/activated, I would like the cli/ansible-devops tools to also select them.

**Comment by durera** [comment]
Manual method is not supported with the modern installer I'm afraid, and as of MAS 8.10 is not supported in the product at all.  We have offered dual manual/subscription mode since introducing OLM support in MAS 8.4 (I think it was 8.4 anyway), but from 8.10 onwards only subscription-based installs are supported.

**Comment by andrercm** [comment]
Closing this as the question is answered, feel free to reopen if any further action is required.
