### ISSUE TITLE
Sizing the MAS deployment requirement with SalesConfigurator

### ISSUE THREAD

**Issue by ekambaraml** [ibm-mas/ansible-devops#753]
MAS is still relies on excel spreadsheet for sizing. Many of the Cloud Pak products are using the https://app.ibmsalesconfigurator.com/#/ for sizing.  Can the MAS team enable the SalesConfigurator for better capacity planning/sizing.

**Comment by andrercm** [comment]
Hi @ekambaraml for the MAS sizing calculator I suggest you to reach out to MAS Product Management team. 

A good place to ask about it and the plans in the roadmap for it is in the [#ask-maximo-suite](https://ibm-watson-iot.slack.com/archives/C014D7K4M5X) slack channel.

I'll close this issue since this has no relationship with the automation work maintained in this GitHub repository.
