### ISSUE TITLE
Automatically trigger master rebuild in ibm-mas/cli

### ISSUE THREAD

**Issue by durera** [ibm-mas/ansible-devops#817]
Trigger master rebuild in ibm-mas/cli when master branch or a new release of this collection is built.

Example of how to do this (it isn't the only way, feel free to use any approach that works):

- https://dev.to/moaaz_adel/github-actions-a-simple-way-to-trigger-workflow-from-another-workflow-1b55

**Comment by whitfiea** [comment]
We should also update the mongo doc that gets saved here https://github.com/ibm-mas/cli/blob/master/image/cli/app-root/save-junit-to-mongo.py#L23 so that it also hasve the ansibleDevopsVersion as well as the cliVersion saved into the mongo doc. Then we can easily see the version of ansible-devops used

**Comment by andrercm** [comment]
Just pending test to ensure we can now store ansible devops version into mongo:
https://github.com/ibm-mas/cli/pull/339

**Comment by andrercm** [comment]
Closing this as requested changes are implemented.
