### ISSUE TITLE
Add checking for internal image registry in Manage installer role

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#819]
Maximo Manage fails to activate if the internal image registry of the OCP cluster is not configured.
I had a hard time figuring out what was causing the activation to fail, but eventually figured out that I didn't configured the image registry 😂.

**Comment by whitfiea** [comment]
@SalaryTheft Thanks for this bug report. This is a problem with the MAS MAnage product itself rather than the ansible-devops component. An internal defect has been raised to address this for the next release of MAS Manage but there is no guarantee it will be fixed by then. For now I will close this issue here as we can't track product defects here.
