### ISSUE TITLE
IoT installation playbook not detecting storage class 

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#843]
![image](https://github.com/ibm-mas/ansible-devops/assets/72844671/0200e2d2-66b4-4ab8-bd72-2a08a68bdc04)

My OCP cluster is using NFS server for persistent storage but above error occured.
I am not sure if `MAS_APP_SETTINGS_IOT_FPL_PVC_STORAGE_CLASS` variable is used for this specific PVC.

**Comment by mudspringhiker** [comment]
I have the same issue. I used rook-ceph to create my storageclasses (I'm installing on Fyre).

**Comment by andrercm** [comment]
Hello, thanks for your feedback!

Regarding auto detection of storage classes, it will only set a storage class for it if it finds any of the following defaulted storage classes defined here: `[ibmc-block-gold, ocs-storagecluster-ceph-rbd, gp2, managed-premium]`
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_app_install/tasks/iot.yml#L39

If none of the above are found, then you must provide export the referred variable to set the storage class: `MAS_APP_SETTINGS_IOT_MQTTBROKER_PVC_STORAGE_CLASS`. We'll implement a change to ensure this variable is defined and not null, which should avoid the issue you faced where IoT installation triggers a PVC without any storage classes defined.

We'll also improve this role's documentation to explicitly describe the environment variable for MessageSight:
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_app_install/defaults/main.yml#L34-L35

**Comment by andrercm** [comment]
Will be fixed by this PR:
https://github.com/ibm-mas/ansible-devops/pull/861

The issue here is that the auto detect logic might not find any available default storage classes, and we dont have anything blocking the installation from beginning if messagesight storage classes are not defined. Therefore this adds an assertion that prevents the iot install from beginning if iot size != dev and storage classes for fpl and message sight are undefined.
I'm also adding a fix for cli to use the common block storage classes for iot related storage classes to ensure it is also passed to iot install ansible roles - that should prevent the issue reported by @mudspringhiker as by default iot will be installed with `small` size and therefore we must have storage classes defined for this type of install:
https://github.com/ibm-mas/cli/pull/328
