### ISSUE TITLE
IoT dev size issue

### ISSUE THREAD

**Issue by aroute** [ibm-mas/ansible-devops#852]
This only happens when the size is dev (small size works fine): `MAS_APP_SETTINGS_IOT_DEPLOYMENT_SIZE=dev` Please check.

```
TASK [ibm.mas_devops.suite_app_install : Install application] ****************************************************************************************
Sunday 04 June 2023  16:53:25 +0000 (0:00:00.030)       0:12:18.871 ***********
fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "IoT maslab: Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"IoT.iot.ibm.com \\\\\"maslab\\\\\" is invalid: spec.settings.messagesight: Invalid value: \\\\\"string\\\\\": spec.settings.messagesight in body must be of type object: \\\\\"string\\\\\"\",\"reason\":\"Invalid\",\"details\":{\"name\":\"maslab\",\"group\":\"iot.ibm.com\",\"kind\":\"IoT\",\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: \\\\\"string\\\\\": spec.settings.messagesight in body must be of type object: \\\\\"string\\\\\"\",\"field\":\"spec.settings.messagesight\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}
```

**Comment by SalaryTheft** [comment]
I had same issue and continuted the installtion on the MAS Core admin page.

**Comment by andrercm** [comment]
Should be fixed with this PR:
https://github.com/ibm-mas/ansible-devops/pull/861

Problem here is that when `MAS_APP_SETTINGS_IOT_DEPLOYMENT_SIZE=dev` then we are trying to [omit the storage class property](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/iot.yml#L17) but it is adding the following for messagesight property (instead of actually omitting the property which is what i believe it was expected):

ok: [localhost] => {
    "mas_app_spec": {
        "bindings": {
            "jdbc": "system",
            "kafka": "system",
            "mongo": "system"
        },
        "components": {},
        "settings": {
            "deployment": {
                "size": "dev"
            },
            "fpl": {
                "functionsexecutor": {
                    "storage": {
                        "class": "",
                        "size": "100Gi"
                    }
                },
                "pipelinerouter": {
                    "storage": {
                        "class": "",
                        "size": "100Gi"
                    }
                }
            },
            **"messagesight": "__omit_place_holder__e23a435d5cb722498559ad2826a808656f242fce"**
        }
    }
}
So after discussing with iot dev team, my change will pass `messagesight.storage.class: ''` if it's dev size and storage is not defined. IoT dev size won't do anything with the storage classes anyway, but at least making this change prevents the IoT CR to fail when installed in the cluster.

**Comment by andrercm** [comment]
Code is merged, will close for now and we can reopen if needed.
