### ISSUE TITLE
Zen Operator install plan not approved automatically while installing CP4D

### ISSUE THREAD

**Issue by SalaryTheft** [ibm-mas/ansible-devops#894]
![image](https://github.com/ibm-mas/ansible-devops/assets/72844671/1a42748d-0bf5-4591-9573-3917232a351f)

```
TASK [ibm.mas_devops.cp4d : install-cp4d : Install CloudPak for Data 4.6.3] **********************************************************************************************
ok: [localhost]

TASK [ibm.mas_devops.cp4d : install-cp4d : Wait for ibm-zen-operator to be ready (60s delay)] ****************************************************************************
FAILED - RETRYING: [localhost]: install-cp4d : Wait for ibm-zen-operator to be ready (60s delay) (20 retries left).
FAILED - RETRYING: [localhost]: install-cp4d : Wait for ibm-zen-operator to be ready (60s delay) (19 retries left).
FAILED - RETRYING: [localhost]: install-cp4d : Wait for ibm-zen-operator to be ready (60s delay) (18 retries left).
...
```
I had to manually approve the install plan for the Zen operator while installing CP4D on OCP 4.10.61.

**Comment by durera** [comment]
Nothing in the collection sets up subscriptions with manual approval enabled in subscriptions, but if you already had set up something in the ibm-common-services namespace using manual approval that will be inherited by all other subscriptions created in that namespace, and will prevent use of this collection because we do not support manual install approvals - they create more problems than they solve, we control operators versions at the catalog level and expect all subscriptions to be following the head of the channel they are subscribed to.

To fix this/continue using this collection find the subscription that was set up with manual approval and switch it to automatic.
