### ISSUE TITLE
oneclick_core loops in task ibm-common-services of the suite_install role for MAS 8.10.3

### ISSUE THREAD

**Issue by aeisma** [ibm-mas/ansible-devops#931]
We are using MAS_UPGRADE_STRATEGY=Manual for a new install of MAS 8.10.3 using the oneclick_core playbook.
Task ibm-common-services of suite_install is called to check each of the ics subscriptions and it loops on the ibm-licensing-operator-app.ibm-common-services subscription.

The IBM Licensing Service operator has indeed not installed.
In the past MAS Core would install the IBM Common Services operator in the core namespace and create an OperandRequest for the IBM Licensing Service. In MAS 8.10.3 neither the ics operator nor the OperandRequest are created.

Is this a new problem in the MAS 8.10.3 operator, or has the dependency on the IBM Licensing Service been removed and should the check for ibm-licensing-operator-app.ibm-common-services be removed from the suite_install role?

Thanks, Aldo

**Comment by durera** [comment]
- We do not support manual upgrade strategy I'm afraid. It causes more problems than it's worth.  There may be still some lingering code in various roles from when it was added.  Control of operator versions for MAS is via catalog selection.
- Latest versions of MAS will no longer declare cloud pak foundation services as a dependency (due to looming breaking changes to be introduced in foundation services that we are trying to avoid impacting MAS).  Foundation Services are still set up by the common-services role.

**Comment by aeisma** [comment]
Please update the documentation for the update strategy (https://ibm-mas.github.io/ansible-devops/roles/convert_to_olm/#mas_upgrade_strategy), remove ibm-licensing-operator-app.ibm-common-services from https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/suite_install/defaults/main.yml.

In case you decide to remove upgrade strategy altogether, it is easy to find where it is used: https://github.com/search?q=repo%3Aibm-mas%2Fansible-devops%20mas_upgrade_strategy&type=code

Thanks, Aldo
