### ISSUE TITLE
oneclick_core unnecessary validation for SLS_LICENSE_ID and SLS_LICENSE_FILE 

### ISSUE THREAD

**Issue by witekwww** [ibm-mas/ansible-devops#962]
oneclick_core returns error if SLS_LICENSE_ID or SLS_LICENSE_FILE is not provided. However, both variables are depraceted with SLS 3.7.0.
Setting SLS_LICENSE_ID variable causes sls role to crash with "When using entitlement_file (SLS 3.7.0 or higher) do not set bootstrap.license_id."

Solution: update oneclick_core pre_tasks - line 31 and 32

**Comment by andrercm** [comment]
thanks for the feedback @witekwww 
can you please share the exported variables used in this case while running `oneclick_core` playbook?
this will help us debug the problem.

**Comment by witekwww** [comment]
@andrercm - sure thing.
when using variables as described in SLS role (https://ibm-mas.github.io/ansible-devops/roles/sls/)
export SLS_ENTITLEMENT_FILE=/mnt/home/license.dat
and running ansible-playbook ibm.mas_devops.oneclick_core
i'm getting error like this:
![image](https://github.com/ibm-mas/ansible-devops/assets/118370754/89fc45b7-3511-45a0-bfa9-e2b1d76a8e76)

however if i remove line 31 and 32 from https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/playbooks/oneclick_core.yml it goes through ok

the solution is to remove verification of SLS_LICENSE_ID var and change verification of SLS_LICENSE_FILE var to SLS_ENTITLEMENT_FILE

**Comment by andrercm** [comment]
So there are some changes we'll have to do to better validate these fields now that SLS 3.7 was introduced.

i think your initial problem was that you might be exporting both `SLS_LICENSE_FILE` (this is likely being set as you said you have to remove line 32 from the [playbook](https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/playbooks/oneclick_core.yml#L32)) and `SLS_ENTITLEMENT_FILE` variables? And currently there's a validation that blocks you from using both as it will be one or the other depending on the SLS version you are using, that's why it is stated:
```
"When using entitlement_file (SLS 3.7.0 or higher) do not set bootstrap.license_id."
```

And also, you are right, `SLS_LICENSE_ID` is still being validated in oneclick_core, which needs fixing as this is not used anymore in SLS 3.7+
As stated in the documentation it will only be used in previous versions of SLS:
```
bootstrap.license_id [Deprecated in SLS 3.7.0]
Defines the License Id to be used to bootstrap SLS. This must be set when bootstrap.license_file is also set and should match the licenseId from the license file. Don't set if you wish to setup entitlement later on. Note: this is now deprecated in SLS 3.7.0. Use this only for versions up to 3.6.0.

Optional unless bootstrap.license_file is set
Environment Variable: SLS_LICENSE_ID
Default: None
```

**Comment by andrercm** [comment]
Closing this issue as it was addresses within the above merged pull requests.
